### ISSUE TITLE
Think about the data structure returned

### ISSUE THREAD

**Issue by yunseorim1116** [tree-s-computer/npm-pack-count#5]
Will the deployment data look like a double array 

`[][]`?
or ,
```
{Name1:[], 
Name2:[]}
```

Someone please comment on whether this looks good.

Currently it's a double array.

I thought it would be easier to make it an array so that I can iterate over it immediately rather than making the iterator an object when I show the data later, either on the front or backend.

But I'm not sure.

Can someone please comment?

**Comment by lukasjhan** [comment]
@yunseorim1116 I like the object one more :)

```ts
{
  Name1:[{downloads, start, end}, {downloads, start, end}, {downloads, start, end}], 
  Name2:[{downloads, start, end}, {downloads, start, end}, {downloads, start, end}]
}
```

**Comment by yunseorim1116** [comment]
Tell me why you thought that way, plz :D

**Comment by lukasjhan** [comment]
I think object is always better when there is no order in data.
It is easier to use using the key.

It's too difficult to find which array belongs to which package. You need to write a complex find function.

**Comment by yunseorim1116** [comment]
ok, I understand, thanks for the feedback.
I'm going to change the data structure to accommodate your suggestion.Thanks.

**Comment by yunseorim1116** [comment]
I've made the changes to the data structure. 
Thanks for the feedback!
